services:
  postgres:
    image: postgres:16-alpine
    container_name: medtrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: medtrack_user
      POSTGRES_PASSWORD: wzMvmPBEp9zD4kg_FA_SgtIuNxfJGFTe
      POSTGRES_DB: medtrack_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: medtrack-redis
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medtrack-backend-container
    depends_on:
      - postgres
      - redis
    env_file: ./backend/.env
    restart: unless-stopped
    expose:
      - "8000"

  frontend:
    build:
      context: ./rx-frontend
      dockerfile: Dockerfile
    container_name: medtrack-frontend-container
    depends_on:
      - backend
    restart: unless-stopped
    expose:
      - "80"

  # NGINX REVERSE PROXY
  nginx:
    image: nginx:latest
    container_name: medtrack-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
